# Generated by Django 5.2.8 on 2025-11-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=120, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('subtitulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=120)),
                ('nivel', models.CharField(max_length=120)),
                ('duracion_horas', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('modalidad', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
